mailbox_file = '/home/harald/git/dracut-mailing/dracut-mailing'
email_from = 'Dracut GitHub Import Bot <github@example.com>'
email_to = 'Developer <dev@example.com>'
email_message_ok = '''Patch set imported to github.
Create a pull request:
<https://github.com/<path_to_master_repo>/compare/master...<pull_repo>:%s>

--
Generated by https://github.com/haraldh/mail2git
'''
email_message_failed = '''Patch set failed to apply to the current HEAD of systemd.

--
Generated by https://github.com/haraldh/mail2git
'''
