mailbox_file = '/home/harald/git/dracut-mailing/dracut-mailing'
github_base_url = 'https://github.com/haraldh/dracut/compare/master...dracut-mailing-devs:'
email_from = 'GitHub Import Bot <github@surfsite.org>'
email_to = 'Harald Hoyer <harald@hoyer.xyz>'
email_message = 'Patchset imported to github.\nPull request:\n'
